// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/uploader/v1/uploader.proto

package upoaderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	FileSize      uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_uploader_v1_uploader_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UploadRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadID) Reset() {
	*x = UploadID{}
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadID) ProtoMessage() {}

func (x *UploadID) ProtoReflect() protoreflect.Message {
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadID.ProtoReflect.Descriptor instead.
func (*UploadID) Descriptor() ([]byte, []int) {
	return file_api_uploader_v1_uploader_proto_rawDescGZIP(), []int{1}
}

func (x *UploadID) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type UploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	TotalChunks   uint32                 `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	UploadUrls    []string               `protobuf:"bytes,3,rep,name=upload_urls,json=uploadUrls,proto3" json:"upload_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReply) Reset() {
	*x = UploadReply{}
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReply) ProtoMessage() {}

func (x *UploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReply.ProtoReflect.Descriptor instead.
func (*UploadReply) Descriptor() ([]byte, []int) {
	return file_api_uploader_v1_uploader_proto_rawDescGZIP(), []int{2}
}

func (x *UploadReply) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadReply) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadReply) GetUploadUrls() []string {
	if x != nil {
		return x.UploadUrls
	}
	return nil
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Progress      uint32                 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_api_uploader_v1_uploader_proto_rawDescGZIP(), []int{3}
}

func (x *StatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusReply) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *StatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_uploader_v1_uploader_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesReply) Reset() {
	*x = FilesReply{}
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesReply) ProtoMessage() {}

func (x *FilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesReply.ProtoReflect.Descriptor instead.
func (*FilesReply) Descriptor() ([]byte, []int) {
	return file_api_uploader_v1_uploader_proto_rawDescGZIP(), []int{5}
}

func (x *FilesReply) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,3,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	TotalChunks   uint32                 `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_uploader_v1_uploader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_uploader_v1_uploader_proto_rawDescGZIP(), []int{6}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *File) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *File) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *File) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_uploader_v1_uploader_proto protoreflect.FileDescriptor

const file_api_uploader_v1_uploader_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/uploader/v1/uploader.proto\x12\vuploader.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n" +
	"\rUploadRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\"'\n" +
	"\bUploadID\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"n\n" +
	"\vUploadReply\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\rR\vtotalChunks\x12\x1f\n" +
	"\vupload_urls\x18\x03 \x03(\tR\n" +
	"uploadUrls\"[\n" +
	"\vStatusReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\rR\bprogress\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\" \n" +
	"\bUserInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"5\n" +
	"\n" +
	"FilesReply\x12'\n" +
	"\x05files\x18\x01 \x03(\v2\x11.uploader.v1.FileR\x05files\"\xe2\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\x1f\n" +
	"\vowner_email\x18\x03 \x01(\tR\n" +
	"ownerEmail\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12!\n" +
	"\ftotal_chunks\x18\x05 \x01(\rR\vtotalChunks\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xcf\x01\n" +
	"\bUploader\x12C\n" +
	"\vStartUpload\x12\x1a.uploader.v1.UploadRequest\x1a\x18.uploader.v1.UploadReply\x12B\n" +
	"\x0fGetUploadStatus\x12\x15.uploader.v1.UploadID\x1a\x18.uploader.v1.StatusReply\x12:\n" +
	"\bGetFiles\x12\x15.uploader.v1.UserInfo\x1a\x17.uploader.v1.FilesReplyBHZFgithub.com/Yulian302/lfusys-services-commons/api/uploader/v1;upoaderv1b\x06proto3"

var (
	file_api_uploader_v1_uploader_proto_rawDescOnce sync.Once
	file_api_uploader_v1_uploader_proto_rawDescData []byte
)

func file_api_uploader_v1_uploader_proto_rawDescGZIP() []byte {
	file_api_uploader_v1_uploader_proto_rawDescOnce.Do(func() {
		file_api_uploader_v1_uploader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_uploader_v1_uploader_proto_rawDesc), len(file_api_uploader_v1_uploader_proto_rawDesc)))
	})
	return file_api_uploader_v1_uploader_proto_rawDescData
}

var file_api_uploader_v1_uploader_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_uploader_v1_uploader_proto_goTypes = []any{
	(*UploadRequest)(nil),         // 0: uploader.v1.UploadRequest
	(*UploadID)(nil),              // 1: uploader.v1.UploadID
	(*UploadReply)(nil),           // 2: uploader.v1.UploadReply
	(*StatusReply)(nil),           // 3: uploader.v1.StatusReply
	(*UserInfo)(nil),              // 4: uploader.v1.UserInfo
	(*FilesReply)(nil),            // 5: uploader.v1.FilesReply
	(*File)(nil),                  // 6: uploader.v1.File
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_uploader_v1_uploader_proto_depIdxs = []int32{
	6, // 0: uploader.v1.FilesReply.files:type_name -> uploader.v1.File
	7, // 1: uploader.v1.File.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: uploader.v1.Uploader.StartUpload:input_type -> uploader.v1.UploadRequest
	1, // 3: uploader.v1.Uploader.GetUploadStatus:input_type -> uploader.v1.UploadID
	4, // 4: uploader.v1.Uploader.GetFiles:input_type -> uploader.v1.UserInfo
	2, // 5: uploader.v1.Uploader.StartUpload:output_type -> uploader.v1.UploadReply
	3, // 6: uploader.v1.Uploader.GetUploadStatus:output_type -> uploader.v1.StatusReply
	5, // 7: uploader.v1.Uploader.GetFiles:output_type -> uploader.v1.FilesReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_uploader_v1_uploader_proto_init() }
func file_api_uploader_v1_uploader_proto_init() {
	if File_api_uploader_v1_uploader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_uploader_v1_uploader_proto_rawDesc), len(file_api_uploader_v1_uploader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_uploader_v1_uploader_proto_goTypes,
		DependencyIndexes: file_api_uploader_v1_uploader_proto_depIdxs,
		MessageInfos:      file_api_uploader_v1_uploader_proto_msgTypes,
	}.Build()
	File_api_uploader_v1_uploader_proto = out.File
	file_api_uploader_v1_uploader_proto_goTypes = nil
	file_api_uploader_v1_uploader_proto_depIdxs = nil
}
