// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/uploader/v1/uploader.proto

package upoaderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Uploader_StartUpload_FullMethodName     = "/uploader.v1.Uploader/StartUpload"
	Uploader_GetUploadStatus_FullMethodName = "/uploader.v1.Uploader/GetUploadStatus"
	Uploader_GetFiles_FullMethodName        = "/uploader.v1.Uploader/GetFiles"
)

// UploaderClient is the client API for Uploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// creates a session for file uploading
type UploaderClient interface {
	// initiates a multipart upload session for a file
	StartUpload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error)
	// gets current upload status
	GetUploadStatus(ctx context.Context, in *UploadID, opts ...grpc.CallOption) (*StatusReply, error)
	// gets all user's files
	GetFiles(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*FilesReply, error)
}

type uploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewUploaderClient(cc grpc.ClientConnInterface) UploaderClient {
	return &uploaderClient{cc}
}

func (c *uploaderClient) StartUpload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadReply)
	err := c.cc.Invoke(ctx, Uploader_StartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploaderClient) GetUploadStatus(ctx context.Context, in *UploadID, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, Uploader_GetUploadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploaderClient) GetFiles(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*FilesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilesReply)
	err := c.cc.Invoke(ctx, Uploader_GetFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploaderServer is the server API for Uploader service.
// All implementations must embed UnimplementedUploaderServer
// for forward compatibility.
//
// creates a session for file uploading
type UploaderServer interface {
	// initiates a multipart upload session for a file
	StartUpload(context.Context, *UploadRequest) (*UploadReply, error)
	// gets current upload status
	GetUploadStatus(context.Context, *UploadID) (*StatusReply, error)
	// gets all user's files
	GetFiles(context.Context, *UserInfo) (*FilesReply, error)
	mustEmbedUnimplementedUploaderServer()
}

// UnimplementedUploaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUploaderServer struct{}

func (UnimplementedUploaderServer) StartUpload(context.Context, *UploadRequest) (*UploadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartUpload not implemented")
}
func (UnimplementedUploaderServer) GetUploadStatus(context.Context, *UploadID) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadStatus not implemented")
}
func (UnimplementedUploaderServer) GetFiles(context.Context, *UserInfo) (*FilesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFiles not implemented")
}
func (UnimplementedUploaderServer) mustEmbedUnimplementedUploaderServer() {}
func (UnimplementedUploaderServer) testEmbeddedByValue()                  {}

// UnsafeUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploaderServer will
// result in compilation errors.
type UnsafeUploaderServer interface {
	mustEmbedUnimplementedUploaderServer()
}

func RegisterUploaderServer(s grpc.ServiceRegistrar, srv UploaderServer) {
	// If the following call panics, it indicates UnimplementedUploaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Uploader_ServiceDesc, srv)
}

func _Uploader_StartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploaderServer).StartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Uploader_StartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploaderServer).StartUpload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Uploader_GetUploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploaderServer).GetUploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Uploader_GetUploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploaderServer).GetUploadStatus(ctx, req.(*UploadID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Uploader_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploaderServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Uploader_GetFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploaderServer).GetFiles(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Uploader_ServiceDesc is the grpc.ServiceDesc for Uploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Uploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uploader.v1.Uploader",
	HandlerType: (*UploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartUpload",
			Handler:    _Uploader_StartUpload_Handler,
		},
		{
			MethodName: "GetUploadStatus",
			Handler:    _Uploader_GetUploadStatus_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _Uploader_GetFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/uploader/v1/uploader.proto",
}
