// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/start_upload.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	FileSize      uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_start_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_start_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_start_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UploadRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	TotalChunks   uint32                 `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	UploadUrls    []string               `protobuf:"bytes,3,rep,name=upload_urls,json=uploadUrls,proto3" json:"upload_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReply) Reset() {
	*x = UploadReply{}
	mi := &file_api_start_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReply) ProtoMessage() {}

func (x *UploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_start_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReply.ProtoReflect.Descriptor instead.
func (*UploadReply) Descriptor() ([]byte, []int) {
	return file_api_start_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadReply) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadReply) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadReply) GetUploadUrls() []string {
	if x != nil {
		return x.UploadUrls
	}
	return nil
}

var File_api_start_upload_proto protoreflect.FileDescriptor

const file_api_start_upload_proto_rawDesc = "" +
	"\n" +
	"\x16api/start_upload.proto\x12\x03api\"K\n" +
	"\rUploadRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\"n\n" +
	"\vUploadReply\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\rR\vtotalChunks\x12\x1f\n" +
	"\vupload_urls\x18\x03 \x03(\tR\n" +
	"uploadUrls2?\n" +
	"\bUploader\x123\n" +
	"\vStartUpload\x12\x12.api.UploadRequest\x1a\x10.api.UploadReplyB\aZ\x05./apib\x06proto3"

var (
	file_api_start_upload_proto_rawDescOnce sync.Once
	file_api_start_upload_proto_rawDescData []byte
)

func file_api_start_upload_proto_rawDescGZIP() []byte {
	file_api_start_upload_proto_rawDescOnce.Do(func() {
		file_api_start_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_start_upload_proto_rawDesc), len(file_api_start_upload_proto_rawDesc)))
	})
	return file_api_start_upload_proto_rawDescData
}

var file_api_start_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_start_upload_proto_goTypes = []any{
	(*UploadRequest)(nil), // 0: api.UploadRequest
	(*UploadReply)(nil),   // 1: api.UploadReply
}
var file_api_start_upload_proto_depIdxs = []int32{
	0, // 0: api.Uploader.StartUpload:input_type -> api.UploadRequest
	1, // 1: api.Uploader.StartUpload:output_type -> api.UploadReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_start_upload_proto_init() }
func file_api_start_upload_proto_init() {
	if File_api_start_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_start_upload_proto_rawDesc), len(file_api_start_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_start_upload_proto_goTypes,
		DependencyIndexes: file_api_start_upload_proto_depIdxs,
		MessageInfos:      file_api_start_upload_proto_msgTypes,
	}.Build()
	File_api_start_upload_proto = out.File
	file_api_start_upload_proto_goTypes = nil
	file_api_start_upload_proto_depIdxs = nil
}
