// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/start_upload.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	FileSize      uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_start_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_start_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_start_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UploadRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadID) Reset() {
	*x = UploadID{}
	mi := &file_api_start_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadID) ProtoMessage() {}

func (x *UploadID) ProtoReflect() protoreflect.Message {
	mi := &file_api_start_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadID.ProtoReflect.Descriptor instead.
func (*UploadID) Descriptor() ([]byte, []int) {
	return file_api_start_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadID) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type UploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	TotalChunks   uint32                 `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	UploadUrls    []string               `protobuf:"bytes,3,rep,name=upload_urls,json=uploadUrls,proto3" json:"upload_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReply) Reset() {
	*x = UploadReply{}
	mi := &file_api_start_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReply) ProtoMessage() {}

func (x *UploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_start_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReply.ProtoReflect.Descriptor instead.
func (*UploadReply) Descriptor() ([]byte, []int) {
	return file_api_start_upload_proto_rawDescGZIP(), []int{2}
}

func (x *UploadReply) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadReply) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadReply) GetUploadUrls() []string {
	if x != nil {
		return x.UploadUrls
	}
	return nil
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Progress      uint32                 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_api_start_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_start_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_api_start_upload_proto_rawDescGZIP(), []int{3}
}

func (x *StatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusReply) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *StatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_start_upload_proto protoreflect.FileDescriptor

const file_api_start_upload_proto_rawDesc = "" +
	"\n" +
	"\x16api/start_upload.proto\x12\x03api\"K\n" +
	"\rUploadRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\"'\n" +
	"\bUploadID\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"n\n" +
	"\vUploadReply\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\rR\vtotalChunks\x12\x1f\n" +
	"\vupload_urls\x18\x03 \x03(\tR\n" +
	"uploadUrls\"[\n" +
	"\vStatusReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\rR\bprogress\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2s\n" +
	"\bUploader\x123\n" +
	"\vStartUpload\x12\x12.api.UploadRequest\x1a\x10.api.UploadReply\x122\n" +
	"\x0fGetUploadStatus\x12\r.api.UploadID\x1a\x10.api.StatusReplyB\aZ\x05./apib\x06proto3"

var (
	file_api_start_upload_proto_rawDescOnce sync.Once
	file_api_start_upload_proto_rawDescData []byte
)

func file_api_start_upload_proto_rawDescGZIP() []byte {
	file_api_start_upload_proto_rawDescOnce.Do(func() {
		file_api_start_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_start_upload_proto_rawDesc), len(file_api_start_upload_proto_rawDesc)))
	})
	return file_api_start_upload_proto_rawDescData
}

var file_api_start_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_start_upload_proto_goTypes = []any{
	(*UploadRequest)(nil), // 0: api.UploadRequest
	(*UploadID)(nil),      // 1: api.UploadID
	(*UploadReply)(nil),   // 2: api.UploadReply
	(*StatusReply)(nil),   // 3: api.StatusReply
}
var file_api_start_upload_proto_depIdxs = []int32{
	0, // 0: api.Uploader.StartUpload:input_type -> api.UploadRequest
	1, // 1: api.Uploader.GetUploadStatus:input_type -> api.UploadID
	2, // 2: api.Uploader.StartUpload:output_type -> api.UploadReply
	3, // 3: api.Uploader.GetUploadStatus:output_type -> api.StatusReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_start_upload_proto_init() }
func file_api_start_upload_proto_init() {
	if File_api_start_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_start_upload_proto_rawDesc), len(file_api_start_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_start_upload_proto_goTypes,
		DependencyIndexes: file_api_start_upload_proto_depIdxs,
		MessageInfos:      file_api_start_upload_proto_msgTypes,
	}.Build()
	File_api_start_upload_proto = out.File
	file_api_start_upload_proto_goTypes = nil
	file_api_start_upload_proto_depIdxs = nil
}
